DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uniq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    name        VARCHAR(255)                                   NOT NULL,
    description TEXT                                           NOT NULL,
    available   BOOLEAN                                        NOT NULL,
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    request_id  BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status     VARCHAR(8),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    text      VARCHAR(512)                                   NOT NULL,
    item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

